
from gif_finder.database.models import Media
from gif_finder.services.media_files.storage import StoredMedia
from gif_finder.services.media_files.inspector import MediaFileInfo


class MediaRepository:
    def get_by_hash(self, content_hash: str) -> Media | None: ...
    def create(self, *, info: MediaFileInfo, stored: StoredMedia, ...) -> Media: ...
    def list(self, *, tag: str | None, author: str | None, stream_id: int | None) -> list[Media]: ...
    def get_tags_for_media(self, media_ids: list[int]) -> dict[int, list[str]]: ...
    def delete(self, media: Media) -> None: ...
