from pathlib import Path


def test_store_hashes_and_copies_a_file(tmp_path: Path): ...
def test_store_is_idempotent_for_identical_content(tmp_path: Path): ...
def test_store_uses_hash_shard_as_storage_key(tmp_path: Path): ...
def test_store_rejects_missing_source(tmp_path: Path): ...
